### ISSUE TITLE
Rollback failed

### ISSUE THREAD

**Issue by jianzzz** [go-gormigrate/gormigrate#53]
goVersion: go1.13.5                        
platform: linux/amd64

Migrations
```
		Rollback: func(tx *gorm.DB) error {
			if err := tx.Migrator().DropColumn("statistic_items", "parent_id"); err != nil {
				return err
			}
			return tx.Migrator().DropColumn("statistic_items", "embed_link")
		},
```
Error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b75d6]

goroutine 1 [running]:
gorm.io/gorm/migrator.Migrator.DropColumn.func1(0xc00024e000, 0xc00024e000, 0xc0001114f8)
	/root/go/pkg/mod/gorm.io/gorm@v1.20.0/migrator/migrator.go:287 +0x46
gorm.io/gorm/migrator.Migrator.RunWithValue(0x7c00000000000000, 0xc0001eaf30, 0xb08d80, 0xc0001b8780, 0x95ff60, 0xaecd40, 0xc000111508, 0xc000111550, 0xc000111540)
	/root/go/pkg/mod/gorm.io/gorm@v1.20.0/migrator/migrator.go:44 +0xb3
gorm.io/gorm/migrator.Migrator.DropColumn(0x8f8800, 0xc0001eaf30, 0xb08d80, 0xc0001b8780, 0x95ff60, 0xaecd40, 0xa2b122, 0x9, 0xc0001b8780, 0xc0001b8780)
	/root/go/pkg/mod/gorm.io/gorm@v1.20.0/migrator/migrator.go:286 +0xba
main.m202011060001.func2(0xc0001eaf30, 0xc0001fb020, 0xc0001fb010)

```

Source Code
![image](https://user-images.githubusercontent.com/8556472/98356185-2d107500-205e-11eb-9217-6bcdb265f135.png)

**Comment by TeaBough** [comment]
Try using the struct pointer instead of a string : 
```
if err := tx.Migrator().DropColumn("users", "my_field"); err != nil {
```
```
if err := tx.Migrator().DropColumn(&User{}, "my_field"); err != nil {
```

**Comment by andreynering** [comment]
Hi @jianzzz,

This seems to be an issue with Gorm and not Gormigrate. I suggest you to open an issue on Gorm's repository.
